name: Validate

on: pull_request

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Install KeepassXC
        run: sudo add-apt-repository ppa:phoerious/keepassxc && sudo apt update && sudo apt install keepassxc
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: purcell/setup-emacs@master
        with:
          version: '27.1'

      - uses: conao3/setup-cask@master
      - name: Run cask
        run: cask
      - name: Run tests
        run: cask exec buttercup -L .
